# cluster-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-example-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-example-sa
    namespace: tekton-ci
roleRef:
  kind: ClusterRole
  name: tekton-triggers-admin
  apiGroup: rbac.authorization.k8s.io
---
# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-example-rolebinding
  namespace: tekton-ci
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-example-sa
    namespace: tekton-ci
roleRef:
  kind: Role
  name: tekton-triggers-example-role
  apiGroup: rbac.authorization.k8s.io
---
# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-example-role
  namespace: tekton-ci
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["triggertemplates", "triggerbindings", "triggers", "interceptors"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create", "get", "list", "watch"]
