[project]
name = "my-app"
version = "0.1.0"
description = "Minimal Python project"
authors = [{ name = "Your Name", email = "your.email@example.com" }]
requires-python = ">=3.9"

[tool.mypy]
python_version = "3.9"
strict = true

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
