apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ parameters.repoUrl.split('/').slice(-1)[0] }}
  description: ${{ parameters.description }}
  annotations:
    github.com/project-slug: ${{ parameters.repoUrl.replace('https://','').replace('http://','') }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: team-a
  lifecycle: experimental
