apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Python app
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: team-a
  lifecycle: experimental
  whatever: ${{ parameters.repoUrl }}
