apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-app-template
  title: Create Python App
  description: Scaffold a new Python app and publish it to GitHub
spec:
  owner: team-a
  type: service

  parameters:
    - title: GitHub Repository
      required:
        - repoOwner
        - repoName
        - description
        - visibility
      properties:
        repoOwner:
          title: GitHub Repository Owner
          type: string
          description: Owner or organization of the repository
        repoName:
          title: GitHub Repository Name
          type: string
          description: Repository name (no spaces or special chars)
        description:
          title: Repository Description
          type: string
        visibility:
          title: Repository Visibility
          type: string
          enum: [public, private]
          default: private

  steps:
    - id: fetch-base
      name: Fetch template base
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: .
        values:
          description: ${{ parameters.description }}
          repoName: ${{ parameters.repoName }}
          repoUrl: ${{ parameters.repoUrl }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: https://github.com/${{ parameters.repoOwner }}/${{ parameters.repoName }}
        description: ${{ parameters.description }}
        repoVisibility: ${{ parameters.visibility }}

    - id: register
      name: Register in Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in Backstage
        icon: catalog
        url: ${{ steps['register'].output.catalogItemUrl }}
