---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: platform-cluster
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
featureGates:
  ImageVolume: true
nodes:
  - role: control-plane
    image: kindest/node:v1.33.2
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 4443
        protocol: TCP
  - role: worker
    image: kindest/node:v1.33.2
    extraMounts:
      - hostPath: /mnt/platform-cluster1  # Host directory to mount
        containerPath: /data       # Mount path inside the KinD node
  - role: worker
    image: kindest/node:v1.33.2
    extraMounts:
      - hostPath: /mnt/platform-cluster2  # Host directory to mount
        containerPath: /data       # Mount path inside the KinD node