---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ubuntu25-packer-image
  description: Ubuntu 25 Packer Image for Harvester
  annotations:
    github.com/project-slug: stuttgart-things/platform-engineering-showcase
  tags:
    - harvester
    - packer
    - ubuntu
spec:
  type: packer-image
  lifecycle: production
  owner: platform-team
