---
apiVersion: v1
kind: Service
metadata:
  name: el-gitea-listener
  namespace: tekton-pipelines
spec:
  type: ClusterIP
  selector:
    eventlistener: el-gitea-listener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080