---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: kyverno-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      serviceAccountName: bibi-sa
      containers:
        - name: app
          image: nginx:1.27
          ports:
            - containerPort: 80
