---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bibi-sa
  namespace: kyverno-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: bibi
  namespace: kyverno-demo
type: Opaque
stringData:
  USERNAME: "alice"
  PASSWORD: "s3cr3t"