apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.db_name }}
  description: Crossplane DB
  tags:
    - kubernetes
    - crossplane
    - infrastructure
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: production-namespace
    # Crossplane specific annotations
    crossplane.io/composite: "true"
    crossplane.io/claim-name: production-namespace-claim
    crossplane.io/claim-namespace: crossplane-system
    crossplane.io/db-name: ${{ values.db_name }}
spec:
  type: resource
  lifecycle: production
  owner: platform-team
  system: infrastructure
  providesApis:
    - kubernetes-api
  links:
    - title: Crossplane Dashboard
      url: https://crossplane.example.com
      icon: dashboard
    - title: Kubernetes Dashboard
      url: https://k8s.example.com
      icon: kubernetes
