---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-ubuntu-plucky
spec:
  template:
    spec:
      containers:
        - name: download-ubuntu-plucky
          image: bash:5.2.2
          command: ["/script/entrypoint.sh"]
          args:
            [
              "https://cloud-images.ubuntu.com/daily/server/plucky/current/plucky-server-cloudimg-amd64.img",
              "/output",
            ]
          volumeMounts:
            - mountPath: /output
              name: hook-artifacts
            - mountPath: /script
              name: configmap-volume
      restartPolicy: OnFailure
      volumes:
        - name: hook-artifacts
          hostPath:
            path: /tmp
            type: DirectoryOrCreate
        - name: configmap-volume
          configMap:
            defaultMode: 0700
            name: download-image
