---
name: check pr
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-python:
    runs-on: dagger
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: '0'

      - name: Call Dagger Function to lint Python code
        uses: dagger/dagger-for-github@v8.1.0
        with:
          version: v0.18.14
          verb: call
          module: github.com/act3-ai/dagger/python@python/v0.1.4
          args: --src . lint --ignore-error=true
