---
name: python lint
on:
  workflow_dispatch:
    inputs:
      branch-name:
        required: false
        default: main
        type: string
        description: Branch to run the workflow on
      runs-on:
        required: false
        type: string
        default: dagger
        description: Runner to use for the workflow
      continue-error:
        default: false
        required: true
        type: boolean
        description: Continue even if the linting fails
      app-directory:
        required: true
        type: string
        default: dagger/python-webapp
        description: Directory of the Python application to lint

jobs:
  lint-python:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: '0'
          ref: ${{ inputs.branch-name }}

      - name: Call Dagger Function to lint Python code
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: v0.18.14
          verb: call
          module: github.com/act3-ai/dagger/python@python/v0.1.4
          args: --src ${{ inputs.app-directory }} lint --ignore-error=${{ inputs.continue-error }}
