name: Lint repo files
on:
  push:
    branches:
    - main
    - feature/*
    - fix/*
  pull_request:
    branches:
    - main
    - feature/*
    - fix/*

jobs:
  lint-repository-files:
    runs-on: ubuntu-latest
    env:
      APP_DIR: "./"                        # Directory to lint
      OUTPUT_FILE: "/tmp/platform-engineering-showcase-lint-findings.txt"
      CONTINUE_ERROR: "true"               # if you want to ignore errors
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Call Dagger Lint Module
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: v0.19.3
          verb: call
          module: github.com/stuttgart-things/blueprints/repository-linting@v1.17.0
          args: validate-multiple-technologies --src ${{ env.APP_DIR }} export --path ${{ env.OUTPUT_FILE }}

      - name: Show lint results
        run: |
          echo "Lint findings:"
          cat ${{ env.OUTPUT_FILE }}
