---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-postgresdb
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: require-dbname-and-rolename
      match:
        resources:
          kinds:
            - resources.stuttgart-things.com/v1alpha1/PostgresDB
      validate:
        message: "PostgresDB must specify 'dbName', 'roleName', and a valid 'deletionPolicy'."
        pattern:
          spec:
            dbName: "?*"
            roleName: "?*"
            deletionPolicy: "?*"

    - name: enforce-deletion-policy
      match:
        resources:
          kinds:
            - resources.stuttgart-things.com/v1alpha1/PostgresDB
      validate:
        message: "'deletionPolicy' must be either 'Orphan' or 'Delete'."
        anyPattern:
          - spec:
              deletionPolicy: "Orphan"
          - spec:
              deletionPolicy: "Delete"